import type { NextPage } from 'next';
import Head from 'next/head';
// import Image from "next/image";

import { Header } from '@/components/layout/Header';
import { Main } from '@/components/layout/Main';
import { HomeMainSection } from '@/components/home/HomeMainSection';
import { HomeTitleContent } from '@/components/home/HomeTitle';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>W-log</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Main className="home-main">
                <HomeMainSection
                    title="I am Alive ✌🏼"
                    titleContent={<HomeTitleContent text="I am Alive ✌🏼" />}
                    description="안녕하세요 서울에서 프론트 엔지니어로 근무중인 김태웅입니다."
                />
            </Main>
        </>
    );
};

export default Home;
